website/auth.py
from flask import Blueprint, render_template, request, flash, url_for, session
from firebase import Firebase
from werkzeug.utils import redirect

sEmails = []
cEmails = []
shopEmails = []

config = {
    "apiKey": "AIzaSyBFxVQa0vfURd8O323Gv-iXdHBxeI3emD8",
    "authDomain": "techzette-9644e.firebaseapp.com",
    "databaseURL": "https://techzette-9644e-default-rtdb.firebaseio.com",
    "storageBucket": "techzette-9644e.appspot.com"
}

firebase = Firebase(config)

auth = Blueprint('auth', __name__)


@auth.route('/addItems', methods=['GET', 'POST'])
def addItems():
    global productArray, product
    email = session.get('e_mail', None)
    # email = request.args.get('Email', None)
    ref_db_items = firebase.database().child("Items")
    ref_db_order = firebase.database().child("Orders")
    ref_db_orders = firebase.database().child("Orders")

    orderList = {}
    haveOrders = False

    ownerNames = []
    users = ref_db_order.get()
    for item in users.each():
        ownerNames.append(item.key())

    if email in ownerNames:
        haveOrders = True

    if haveOrders:
        productList = ref_db_orders.child(email).child('orders').get()
        # array stored with product names
        productArray = productList.val().split("+")
        # print(productArray[0])
        for i in range(len(productArray)):
            product = productArray[i].split("?")
            orderList[i] = product

    if request.method == 'POST':
        brand = request.form.get('brand')
        name = request.form.get('name')
        description = request.form.get('description')
        price = request.form.get('price')
        image = request.form.get('image')
        category = request.form.get('category')

        if len(brand) < 1:
            flash('Brand name must be greater than 1 characters', category='error')
        elif len(name) < 2:
            flash('Product name must be greater than 1 character', category='error')
        elif len(description) < 7:
            flash('Description must be atleast 10 characters', category='error')
        elif len(image) < 2:
            flash('Image URL must be greater than 1 character', category='error')
        elif int(price) <= 0:
            flash('Price must be atleast LKR 1', category='error')
        else:
            # add user to database
            data = {
                'Brand': brand,
                'Name': name,
                'Description': description,
                'Price': price,
                'URL': image,
                'Owner': email,
                'Category': category
            }
            ref_db_items.child(name).set(data)
            flash('Item added Successfully!', category='success')
    if haveOrders:
        return render_template("addItems.html", Email=email, products=orderList, haveOrders=haveOrders, length=len(productArray))
    else:
        return render_template("addItems.html", Email=email, haveOrders=haveOrders)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    ref_db_sellers = firebase.database().child("Sellers")
    ref_db_customers = firebase.database().child("Customers")

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        sellerNames = ref_db_sellers.get()
        for sell in sellerNames.each():
            sEmails.append(sell.key())
        customerNames = ref_db_customers.get()
        for sell in customerNames.each():
            cEmails.append(sell.key())
        if email in sEmails:
            fullList = sellerNames.val()
            if fullList[email]["Password"] == password:
                session['e_mail'] = email
                return redirect(request.args.get("next") or url_for("auth.addItems", Email=email))
                # return redirect(request.args.get("next") or url_for("auth.addItems"))
            else:
                flash('Recheck your password!', category='error')
                return render_template("login.html")
        elif email in cEmails:
            fullList = customerNames.val()
            if fullList[email]["Password"] == password:
                session['e_mail'] = email
                # return redirect(request.args.get("next") or url_for("views.home", Email=email))
                return redirect(request.args.get("next") or url_for("views.ecommerce"))
            else:
                flash('Recheck your password!', category='error')
                return render_template("login.html")
        else:
            flash('Account not found!', category='error')

    return render_template("login.html")


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    ref_db_sellers = firebase.database().child("Sellers")
    ref_db_seller = firebase.database().child("Sellers")
    ref_db_customers = firebase.database().child("Customers")
    ref_db_customer = firebase.database().child("Customers")

    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        accType = request.form.get('acc_type')

        sellerNames = ref_db_seller.get()
        for sell in sellerNames.each():
            sEmails.append(sell.key())
        customerNames = ref_db_customer.get()
        for sell in customerNames.each():
            cEmails.append(sell.key())

        if len(email) < 4:
            flash('Username must be greater than 4 characters', category='error')
        elif len(firstName) < 2:
            flash('First name must be greater than 1 character', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 3:
            flash('Password must be atleast 7 characters', category='error')
        else:
            # add user to database
            if email in sEmails:
                flash('User account already exists!', category='error')
            elif email in cEmails:
                flash('User account already exists!', category='error')
            else:
                if '.' in email:
                    flash('Use "dot" as word instead of character "."!', category='error')
                else:
                    if accType == 'seller':
                        seller = {
                            'Email': email,
                            'Name': firstName,
                            'Password': password1,
                        }
                        ref_db_sellers.child(email).set(seller)
                    else:
                        seller = {
                            'Email': email,
                            'Name': firstName,
                            'Password': password1,
                        }
                        ref_db_customers.child(email).set(seller)
                    flash('Account created!', category='success')

    return render_template("sign_up.html")


@auth.route('/sign-up2', methods=['GET', 'POST'])
def sign_up2():
    ref_db_sellers = firebase.database().child("Sellers")
    ref_db_seller = firebase.database().child("Sellers")
    ref_db_customers = firebase.database().child("Customers")
    ref_db_customer = firebase.database().child("Customers")

    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        accType = request.form.get('acc_type')

        sellerNames = ref_db_seller.get()
        for sell in sellerNames.each():
            sEmails.append(sell.key())
        customerNames = ref_db_customer.get()
        for sell in customerNames.each():
            cEmails.append(sell.key())

        if len(email) < 4:
            flash('Username must be greater than 4 characters', category='error')
        elif len(firstName) < 2:
            flash('First name must be greater than 1 character', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 3:
            flash('Password must be atleast 7 characters', category='error')
        else:
            # add user to database
            if email in sEmails:
                flash('User account already exists!', category='error')
            elif email in cEmails:
                flash('User account already exists!', category='error')
            else:
                if '.' in email:
                    flash('Use "dot" as word instead of character "."!', category='error')
                else:
                    if accType == 'seller':
                        seller = {
                            'Email': email,
                            'Name': firstName,
                            'Password': password1,
                        }
                        ref_db_sellers.child(email).set(seller)
                    else:
                        seller = {
                            'Email': email,
                            'Name': firstName,
                            'Password': password1,
                        }
                        ref_db_customers.child(email).set(seller)
                    flash('Account created!', category='success')

    return render_template("sign_up2.html")


@auth.route('/login2', methods=['GET', 'POST'])
def login2():
    ref_db_sellers = firebase.database().child("Sellers")
    ref_db_customers = firebase.database().child("Customers")
    ref_db_shops = firebase.database().child("Shops")

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        sellerNames = ref_db_sellers.get()
        for sell in sellerNames.each():
            sEmails.append(sell.key())
        shopNames = ref_db_shops.get()
        for sell in shopNames.each():

website/templates/addItems2.html
{% extends "base2.html" %}
{% block style %}

{% endblock %}
{% block title %}TechZette - Add Items{% endblock %}
{% if Email != None %}
        {% block name %}{{ Email }}{% endblock %}
{% endif %}
{% block content %}

<!-- Section 1 -->
<section class="w-full">

    <div class="mx-auto max-w-7xl">
        <div class="flex flex-col lg:flex-row">
            <div class="w-full lg:w-12/12 xl:w-12/12">
                    <form method="POST">
                <div class="flex flex-col items-start justify-start w-full h-full p-10 lg:p-16 xl:p-24">

                    <h1 class="mb-1 text-4xl font-extrabold leading-none text-yellow-400 lg:text-5xl xl:text-6xl sm:mb-3 uppercase">Add your products</h1>
                    <div class="relative w-full mt-10 space-y-4 bg-gray-800 py-10 px-10 rounded-xl">
                        <div class="relative">
                            <label class="font-medium text-white text-2xl">Brand</label>
                            <input id="brand" name="brand" type="text" class="block w-full px-4 py-4 mt-2 text-s placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Brand Name">
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white text-2xl">Product Name</label>
                            <input type="text" id="name" name="name" class="block w-full px-4 py-4 mt-2 text-s placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Product Name" minlength="24" maxlength="42">
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white text-2xl">Description</label>
                            <input type="text" id="description" name="description" class="block w-full px-4 py-10 mt-2 text-s placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Description" maxlength="510" minlength="380">
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white text-2xl">Image URL</label>
                            <input type="text" id="image" name="image" class="block w-full px-4 py-4 mt-2 text-s placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Image URL">
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white text-2xl">Price</label>
                            <input type="text" id="price" name="price" class="block w-full px-4 py-4 mt-2 text-s placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Price">
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white text-2xl">Category</label>
                            <select name="category" class="block w-full px-4 py-4 mt-2 text-xl placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50 mb-10">
                                <option value="laptops">Laptop</option>
                                <option value="processors">Processors</option>
                                <option value="memory">Memory(RAM)</option>
                                <option value="graphic">Graphic Cards</option>
                                <option value="monitors">Monitors</option>
                                <option value="motherboard">Motherboard</option>
                                <option value="mouse">Mouse and Keyboards</option>
                                <option value="storages">Storages</option>
                                <option value="powersupply">Power Supply</option>
                                <option value="other">Other</option>
                            </select>
                        </div>

                        <div class="relative mx-auto">
                                <button type="submit" class="mr-6 inline-block px-16 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease">Add</button>
<!--                                <a href="/remove2" class="inline-block px-16 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease">Remove >></a>-->
                                <a href="/remove2" class="mr-10 inline-block px-10 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease">Remove >></a>

                        </div>
                    </div>

                </div>
                    </form>

            </div>
                {% if haveOrders %}
            <div class="w-full bg-gray-200 lg:w-6/12 xl:w-7/12 mt-10 mb-10 rounded-xl">
                <div class="flex flex-col items-start justify-start w-full h-full p-10 lg:p-16 xl:p-18">
                    <h4 class="w-full text-3xl font-bold">ORDERS</h4>
                        {% for i in range(length) %}
                    <div class="relative w-full mt-10 space-y-1 ">
                        <div class="relative">
                            <label class="font-medium text-gray-900">Product:</label><label class="font-medium text-gray-900 ml-5">{{ products[i][3] }}</label>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-gray-900">Name: </label><label class="font-medium text-gray-900 ml-9">{{ products[i][0] }}</label>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-gray-900">Address:</label><label class="font-medium text-gray-900 ml-6">{{ products[i][1] }}</label>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-gray-900">Contact: </label><label class="font-medium text-gray-900 ml-6">{{ products[i][2] }}</label>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-gray-900">Payment:</label><label class="font-medium text-gray-900 ml-5">{{ products[i][4] }}</label>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-gray-900">Quantity:</label><label class="font-medium text-gray-900 ml-5">{{ products[i][5] }}</label>
                        </div>

                    </div>
                        {% endfor %}

                </div>
            </div>
                {% endif %}
        </div>
    </div>

</section>

{% endblock %}

website/templates/graphic.html
{% extends "base.html" %}
{% block title %}TechZette - Accessories{% endblock %}
{% block style %}

{% endblock %}
{% if Email != None %}
        {% block name %}{{ Email }}{% endblock %}
{% endif %}

{% block content %}


<section class="w-full">
    <div class="w-full px-5 py-10 mx-auto sm:py-12 md:py-16 md:px-10 max-w-7xl">

        <h1 class="mb-1 text-4xl font-extrabold leading-none text-yellow-300 lg:text-5xl xl:text-6xl sm:mb-3">Graphic Cards</h1>
<!--        <p class="text-lg font-medium text-gray-500 sm:text-2xl">Designs and layouts to help you with your app.</p>-->
        <div class="flex grid h-full grid-cols-12 gap-10 pb-10 mt-8 sm:mt-16">
            {% for name in nameList %}
            {% if productList[name]['Category'] == 'graphic' %}
            <div class="transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-110 relative flex flex-col items-start justify-end h-100 col-span-12 overflow-hidden rounded-xl group md:col-span-6 xl:col-span-4">
                <div class="relative z-20 w-full h-auto py-8 text-white bg-white border-t-0 border-white px-7 rounded-t-xl">
                    <a href="#_" class="block w-full bg-center bg-cover h-80" style="background-image:url({{productList[name]['URL']}})"></a>
                </div><div class="relative z-20 w-full h-auto py-8 text-white bg-gray-800 border-t-0 border-white px-7">
                    <h2 class="mb-5 text-2xl font-bold">{{productList[name]['Name']}}</h2>
                    <p class="mb-1 text-lg font-normal text-white opacity-100">Price: {{productList[name]['Price']}}LKR</p>
<!--                    <div class="flex grid h-full grid-cols-2 gap-4">-->
                        <div class="relative">
                            <form method="POST">
                            <button type="submit" value="{{productList[name]['Name']}}" name="product" class="inline-block w-full px-5 py-2 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease mt-5">More Info</button>
                            </form>
                        </div>
<!--                        <div class="relative">-->
<!--                            <form method="POST">-->
<!--                                <label for="quantity" >Qty:</label>-->
<!--                                <input type="number" class="text-black" value="1" id="quantity" name="quantity" min="1" max="10">-->
<!--                                <button type="submit" value="{{productList[name]['Name']}}" name="cart" class="inline-block w-full px-5 py-2 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease mt-5">Add to Cart</button>-->
<!--                            </form>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>

            </div>
            {% endif %}
                {% endfor %}

            </div>
            </div>
        </div>
    </div>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/2.8.0/alpine.js"></script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}TechZette - Login{% endblock %}

{% block content %}
<!-- Section 1 -->
<section class="w-full bg-gray-800">

    <div class="mx-auto ">
        <div class="flex flex-col lg:flex-row">
            <div class="w-full lg:w-6/12 xl:w-7/12 bg-gradient-to-r from-white via-white to-gray-100" style="background-image: url(https://images.unsplash.com/photo-1465982046896-5172ca240f27?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80); background-repeat: no-repeat;">
                <div class="flex flex-col items-center justify-center w-full h-full px-10 my-20 lg:px-16 lg:my-0">
                    <div class="flex flex-col items-start space-y-8 tracking-tight lg:max-w-3xl">
                        <div class="relative">
                            <h2 class="text-5xl font-bold text-white xl:text-6xl">TECHZETTE</h2>
                        </div>
                        <p class="text-2xl text-white">Build your PC from us with popular <b>Brands</b> and <b>Tech companies</b> in <b>Sri Lanka</b>.</p>
                    </div>
                </div>
            </div>

            <div class="w-full bg-gray-800 lg:w-6/12 xl:w-5/12">
                <div class="flex flex-col items-start justify-start w-full h-full p-10 lg:p-16 xl:p-24">
                    <h4 class="w-full text-3xl font-bold text-white">Login</h4>
                    <p class="text-lg text-gray-200">or, if you don't have an account you can <a href="/sign-up" class="text-yellow-400 underline">Sign Up</a></p>
					<form class="login100-form validate-form" method="POST" action="{{ url_for('auth.login') }}">
                    <div class="relative w-full mt-10 space-y-8">
                        <div class="relative">
                            <label class="font-medium text-white">Username</label>
                            <input id="email" name="email" type="text" class="block w-80 px-4 py-4 mt-2 text-xl placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Your Username" required>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white">Password</label>
                            <input id="password" name="password" type="password" class="block w-full px-4 py-4 mt-2 text-xl placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Your Password" required>
                        </div>

                        <div class="relative">
							<button type="submit" class="inline-block w-full px-5 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease mt-10">Login</button>
<!--                            <a type="submit" class="inline-block w-full px-5 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease mt-10">Login</a>-->
                        </div>
                    </div>
					</form>
                </div>
            </div>
        </div>
    </div>

</section>



<!--<div class="limiter">-->
<!--		<div class="container-login100 page-holder bg-cover" style="background-image: url('{{ url_for('static',filename='images/bg-01.jpg') }}');">-->
<!--			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">-->
<!--				<form class="login100-form validate-form" method="POST" action="{{ url_for('auth.login') }}">-->
<!--					<span class="login100-form-title p-b-49">-->
<!--						Login-->
<!--					</span>-->

<!--					<div class="wrap-input100 validate-input m-b-23" data-validate = "Email is required">-->
<!--						<span class="label-input100">Email</span>-->
<!--						<input class="input100" type="email" id="email" name="email" placeholder="Type your Email">-->
<!--						<span class="focus-input100" data-symbol="&#xf206;"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input100 validate-input" data-validate="Password is required">-->
<!--						<span class="label-input100">Password</span>-->
<!--						<input class="input100" type="password" id="password" name="password" placeholder="Type your password">-->
<!--						<span class="focus-input100" data-symbol="&#xf190;"></span>-->
<!--					</div>-->

<!--					<div class="text-right p-t-8 p-b-31">-->
<!--						<a href="#">-->
<!--							Forgot password?-->
<!--						</a>-->
<!--					</div>-->

<!--					<div class="container-login100-form-btn">-->
<!--						<div class="wrap-login100-form-btn">-->
<!--							<div class="login100-form-bgbtn"></div>-->
<!--							<button class="login100-form-btn">-->
<!--								Login-->
<!--							</button>-->
<!--						</div>-->
<!--					</div>-->

<!--					<div class="flex-col-c p-t-20">-->
<!--						<span class="txt1 p-b-17">-->
<!--							Or Sign Up Using-->
<!--						</span>-->

<!--						<a href="/sign-up" class="txt2">-->
<!--							Sign Up-->
<!--						</a>-->
<!--					</div>-->
<!--				</form>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->


<!--	<div id="dropDownSelect1"></div>-->
{% endblock %}

website/templates/login2.html
{% extends "base2.html" %}
{% block title %}TechZette - Login{% endblock %}
{% block content %}
<!-- Section 1 -->
<section class="w-full bg-gray-800">

    <div class="mx-auto">
        <div class="flex flex-col lg:flex-row">
            <div class="relative w-full lg:w-6/12 xl:w-7/12 bg-gradient-to-r from-white via-white to-gray-100" style="background-image: url(https://wallpapercave.com/wp/wp2888523.jpg); background-repeat: no-repeat;">
                <div class="relative flex flex-col items-center justify-center w-full h-full px-10 my-20 lg:px-16 lg:my-0">
                    <div class="flex flex-col items-start space-y-8 tracking-tight lg:max-w-3xl">
                        <div class="relative">
                            <h2 class="text-5xl font-bold text-white xl:text-6xl">TECHZETTE</h2>
                        </div>
                        <p class="text-2xl text-white">Build your PC from us with popular <b>Brands</b> and <b>Tech companies</b> in <b>Sri Lanka</b>.</p>
                    </div>
                </div>
            </div>

            <div class="w-full bg-gray-800 lg:w-6/12 xl:w-5/12">
                <div class="flex flex-col items-start justify-start w-full h-full p-10 lg:p-16 xl:p-24">
                    <h4 class="w-full text-3xl font-bold text-white">Login</h4>
                    <p class="text-lg text-gray-200">or, if you don't have an account you can <a href="/sign-up2" class="text-yellow-400 underline">Sign Up</a></p>
					<form class="login100-form validate-form" method="POST" action="{{ url_for('auth.login2') }}">
                    <div class="relative w-full mt-10 space-y-8">
                        <div class="relative">
                            <label class="font-medium text-white">Username</label>
                            <input id="email" name="email" type="text" class="block w-80 px-4 py-4 mt-2 text-xl placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Your Username" required>
                        </div>
                        <div class="relative">
                            <label class="font-medium text-white">Password</label>
                            <input id="password" name="password" type="password" class="block w-full px-4 py-4 mt-2 text-xl placeholder-gray-400 bg-gray-200 rounded-lg focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50" placeholder="Enter Your Password" required>
                        </div>

                        <div class="relative">
							<button type="submit" class="inline-block w-full px-5 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease mt-10">Login</button>
<!--                            <a type="submit" class="inline-block w-full px-5 py-4 text-lg font-medium text-center text-white transition duration-200 bg-blue-600 rounded-lg hover:bg-blue-700 ease mt-10">Login</a>-->
                        </div>
                    </div>
					</form>
                </div>
            </div>
        </div>
    </div>

</section>



<!--<div class="limiter">-->
<!--		<div class="container-login100 page-holder bg-cover" style="background-image: url('{{ url_for('static',filename='images/bg-01.jpg') }}');">-->
<!--			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">-->
<!--				<form class="login100-form validate-form" method="POST" action="{{ url_for('auth.login') }}">-->
<!--					<span class="login100-form-title p-b-49">-->
<!--						Login-->
<!--					</span>-->

<!--					<div class="wrap-input100 validate-input m-b-23" data-validate = "Email is required">-->
<!--						<span class="label-input100">Email</span>-->
<!--						<input class="input100" type="email" id="email" name="email" placeholder="Type your Email">-->
<!--						<span class="focus-input100" data-symbol="&#xf206;"></span>-->
<!--					</div>-->

<!--					<div class="wrap-input100 validate-input" data-validate="Password is required">-->
<!--						<span class="label-input100">Password</span>-->
<!--						<input class="input100" type="password" id="password" name="password" placeholder="Type your password">-->
<!--						<span class="focus-input100" data-symbol="&#xf190;"></span>-->
<!--					</div>-->

<!--					<div class="text-right p-t-8 p-b-31">-->
<!--						<a href="#">-->
<!--							Forgot password?-->
<!--						</a>-->
<!--					</div>-->

<!--					<div class="container-login100-form-btn">-->
<!--						<div class="wrap-login100-form-btn">-->
<!--							<div class="login100-form-bgbtn"></div>-->
<!--							<button class="login100-form-btn">-->
<!--								Login-->
<!--							</button>-->
<!--						</div>-->
<!--					</div>-->

<!--					<div class="flex-col-c p-t-20">-->
<!--						<span class="txt1 p-b-17">-->
<!--							Or Sign Up Using-->
<!--						</span>-->

<!--						<a href="/sign-up" class="txt2">-->
<!--							Sign Up-->
<!--						</a>-->
<!--					</div>-->
<!--				</form>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->


<!--	<div id="dropDownSelect1"></div>-->
{% endblock %}